# Generated by Django 3.2.9 on 2021-12-10 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('pinned', models.BooleanField(default=False)),
                ('written_on', models.DateField(auto_now=True)),
                ('rich_txt', models.TextField(default=' ', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superuser', models.BooleanField(default=False)),
                ('pseudo_name', models.CharField(max_length=16, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('mail_address', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.articles')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.users')),
            ],
        ),
        migrations.CreateModel(
            name='Community_moderator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.users')),
                ('community_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.community')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_on', models.DateField(auto_now=True)),
                ('rich_txt', models.TextField(default=' ', max_length=100)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.articles')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.users')),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.users'),
        ),
        migrations.AddField(
            model_name='articles',
            name='community_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.community'),
        ),
    ]
