# Generated by Django 3.2.9 on 2021-12-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('community_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('superuser', models.BooleanField(default=False)),
                ('pseudo_name', models.CharField(max_length=16)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('mail_address', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
    ]
