# Generated by Django 3.2.9 on 2021-12-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='article_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
