# Generated by Django 3.2.9 on 2022-03-08 16:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articles',
            name='deleted_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 16, 58, 13, 872544, tzinfo=utc)),
        ),
    ]
