# Generated by Django 3.2.9 on 2021-12-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_articles_article_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_num',
            field=models.IntegerField(unique=True),
        ),
    ]
