# Generated by Django 3.2.9 on 2021-12-17 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_remove_articles_article_num'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='community_moderator',
            unique_together={('community_id', 'admin_id')},
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('article_id', 'user_id')},
        ),
    ]
